### ISSUE TITLE
Cleanup data structures

### ISSUE THREAD

**Issue by hdrake** [hdrake/ClimateMARGO.jl#14]
Before tackling documentation https://github.com/hdrake/ClimateMARGO.jl/issues/2 and unit tests https://github.com/hdrake/ClimateMARGO.jl/issues/3, the first priority is to cleanup the data structures (see branch https://github.com/hdrake/ClimateMARGO.jl/tree/data-structure-cleanup).

There are a few features which are particularly undesirable about the current data structures:

1. We hardly use any functions in the JuMP optimization code `src/optimization/jl`, instead choosing to write out the objective function in its entirety, which is excessively long and susceptible to bugs. My guess is that it is possible to write the objective condition in one line that looks something like (in pseudo-JuMP syntax)
```julia
for i in N; @constraint{ T(M,R,G,A) < Tstar }; end
```
where `M`, `R`, `G`, `A` are the control variables.
2. The few functions that *are* currently used in the JuMP optimization code have explicitly re-defined within the optimization code, probably for legacy reasons. Ideally, the diagnostic functions used for plotting / analysis should be re-used for the optimization to reduce the likelihood of discrepancies between the two versions of the code (which indeed caused breaking bugs in early versions of the implementation).
3. There are a lot of redundant functions that should be collapsed into a single function with keyword arguments and/or different methods.
4. We should rethink the `ClimateModel`, `Physics`, `Controls`, and `Economics` structs. They are fairly unwieldy because I did not really understand Julia constructors when I created them half a year ago. It might be useful to look at how more mature julia models like https://github.com/CliMA/Oceananigans.jl or https://github.com/CliMA/ClimateMachine.jl structure their submodules for inspiration.

**Comment by hdrake** [comment]
About the model default values, eventually I want to move away from hard-coding this anywhere, whether in `default.jl` or directly in the constructor. Instead, I think it would be better to have the defaults in a `.yml` or `.csv` file. This would also be nice because it would make for easy sharing of parameter configurations.

For example, I imagine you could email me your run-time parameter `fonsp_favorite.yml` file and you could just run:
```julia
ClimateModel(parameter_file = "fonsp_favorite.yml")
```
or something similar.

I don't think this would take any more work than hard-coding right into the constructor but may be a more desirable approach for the long-term. What do you think?

**Comment by fonsp** [comment]
Oh that's a cool idea! I'd recommend JSON over yaml/csv - since JSON can contain nested data structures:

The package `JSON2.jl` can directly read JSON files/strings into Julia types:

![image](https://user-images.githubusercontent.com/6933510/84398646-7f10b400-ac00-11ea-8d6d-501be1c5c13c.png)

**Comment by hdrake** [comment]
That is really convenient! It would be great to have human-readable and easily modifiable input files that uniquely determine a MARGO configuration!

**Comment by hdrake** [comment]
A lot of this has not been implemented in https://github.com/hdrake/ClimateMARGO.jl/pull/19, but it is still a work-in-progress.
